var _e={f_finalize:function(){var e
this._n1=e},tu:function(e){var t=this
if(!t._X){e.call(t,t)
return}t._n1=e},of:function(){var n,r=this,e=r._n1
if(!e)return!1
r._n1=n
try{e.call(r,r)}catch(t){f_core.error(fa_commands,"Call of callback: "+e+" throws exception.",t)
return!1}return!0}}
var fa_commands=new f_aspect("fa_commands",null,_e);